// <auto-generated />
using System;
using BackendWT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendWT.Migrations
{
    [DbContext(typeof(WatchTrackerContext))]
    [Migration("20210202162342_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackendWT.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "jolame",
                            Birthday = new DateTime(2021, 2, 2, 17, 23, 42, 235, DateTimeKind.Local).AddTicks(4650),
                            Email = "jolame@gmail.es",
                            Name = "Jose",
                            Password = "1234",
                            Surname = "Lacueva"
                        },
                        new
                        {
                            UserId = "alalma",
                            Birthday = new DateTime(2021, 2, 2, 17, 23, 42, 237, DateTimeKind.Local).AddTicks(4651),
                            Email = "alvaro@gmail.com",
                            Name = "Alvaro",
                            Password = "1234",
                            Surname = "Alepuz"
                        });
                });

            modelBuilder.Entity("BackendWT.Models.UserMovies", b =>
                {
                    b.Property<int>("UserMoviesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UserDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserVote")
                        .HasColumnType("int");

                    b.HasKey("UserMoviesId");

                    b.HasIndex("UserId");

                    b.HasIndex("MovieId", "UserId")
                        .IsUnique();

                    b.ToTable("UserMovies");

                    b.HasData(
                        new
                        {
                            UserMoviesId = 1,
                            MovieId = 1726,
                            UserDate = new DateTime(2021, 2, 2, 17, 23, 42, 237, DateTimeKind.Local).AddTicks(4651),
                            UserId = "jolame",
                            UserStatus = "Watched",
                            UserVote = 9
                        },
                        new
                        {
                            UserMoviesId = 2,
                            MovieId = 557,
                            UserDate = new DateTime(2021, 2, 2, 17, 23, 42, 237, DateTimeKind.Local).AddTicks(4651),
                            UserId = "jolame",
                            UserStatus = "Watching",
                            UserVote = 10
                        },
                        new
                        {
                            UserMoviesId = 3,
                            MovieId = 557,
                            UserDate = new DateTime(2021, 2, 2, 17, 23, 42, 237, DateTimeKind.Local).AddTicks(4651),
                            UserId = "alalma",
                            UserStatus = "Watching",
                            UserVote = 8
                        });
                });

            modelBuilder.Entity("BackendWT.Models.UserMovies", b =>
                {
                    b.HasOne("BackendWT.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
